[Feature]: lastArtworkId 이전의 questionAnswer들을 DB에서 불러온다.
DeveloperAcademy-POSTECH/MacC_Team_Beartear pull request #111
Opened 2022-11-25 02:38 UTC by rriver2

## Close Issues
- Pull Request와 관련된 Issue가 있다면 나열합니다.
🔒 Close #102

## 작업 내용 (Content)
- 작업한 내용을 나열 후 설명
- #102 이슈 참고해주세요 !
- #99 이후 lastArtworkId 이전의 questionAnswer들도 DB에서 불러오는 작업이 추가적으로 필요했습니다.
- 그래서 lastArtworkId 이전의 questionAnswer들을 DB에서 불러오는 QuestionAnswerRepository과 FetchQuestionAnswerUsecase을 구현했습니다 ..!

## Review points
- 리뷰어가 중점적으로 리뷰해줬으면 하는 포인트
- 하단의 기타 사항 참고

## 기타 사항 (Etc)
- 작업하면서 고민이 되었던 부분이나 질문 사항 등
- Artworks의 subCollection, QuestionAnswers에 접근을 해서 가지고 온 questionAnswer을 list 합쳐야 하는 과정에서 어려움이 있었습니다.
<img width="830" alt="스크린샷 2022-11-25 오전 11 32 38" src="https://user-images.githubusercontent.com/82457928/203888705-cdce98c3-8b7b-481a-8caf-004b4d9abfcf.png">
Zip이라는 operator를 써서 구현을 했는데, 이게 가장 좋은 방법이었는지 잘 모르겠습니다. 더 좋은 방법이 있다면 알려주세요..!
<img width="691" alt="스크린샷 2022-11-25 오전 11 34 45" src="https://user-images.githubusercontent.com/82457928/203888978-e5a5c98f-6414-4901-9d35-06b096a9a77b.png">

## 관련 사진 gif 및 (Optional)

## References (Optional)
- 참고한 사이트나 정리한 wiki 링크를 넣어주세요

2022-11-25 02:39 UTC, rriver2 commented on Gom4ziz/Source/Constants/CollectionName.swift
> +    }
[entity 구조를 변경했던 PR](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/issues/99)에서 추가했어야 하는 코드였는데 이번 PR에서 commit 날리게 됐습니다 🥲🙏🏻🥹

2022-11-25 02:58 UTC, HoJongE requested changes
고생하셨습니다!!
concat은 직렬적으로 비동기 요청하는 것으로 알고 있는데, 따라서 불러오는 속도가 많이 느린 것으로 알고 있습니다. 
다른 operator를 사용해보시는게 좋을 것 같아요

2022-11-25 02:58 UTC, HoJongE commented on Gom4ziz/Source/Data/Repository/FirebaseQuestionAnswerRepository.swift
> +            returnQuestionAnswer = returnQuestionAnswer.concat(questionAnswer)
[수정 필수]
concat은 이전 요청이 끝나면 다음 요청을 하는 operator로, 작업이 직렬적으로 일어나기 때문에 시간이 매우 오래 걸릴 수 있습니다. 병렬적으로 요청할 수 있는 operator를 사용해보세요. 아마 merge일 겁니다. merge 한 후 toArray 함수를 호출하면 병렬적으로 오는 
QuestionAnswer데이터들을 배열로 변환할 수 있는 것으로 알고 있습니다.

2022-11-25 02:58 UTC, HoJongE commented on Gom4ziz/Source/Data/Repository/FirebaseQuestionAnswerRepository.swift
> +        var returnQuestionAnswer: Observable<[QuestionAnswer]> = Observable.empty()
[질문]
empty인 Observable은 왜 있는 건가요??

2022-11-25 03:01 UTC, SH0123 commented on Gom4ziz/Source/Data/Repository/FirebaseQuestionAnswerRepository.swift
> +            let questionAnswer = Observable<QuestionAnswer>.zip([getQuestionAnswerListRef(for: userId, before: artworkId)
[질문]
제 생각에는 question answer를 merge만 하면 되는게 아닌가 하는데 zip은 왜 사용된건가요?? 이해시켜주세요 ㅠㅠ

2022-11-25 05:05 UTC, rriver2 commented on Gom4ziz/Source/Data/Repository/FirebaseQuestionAnswerRepository.swift
> +            let questionAnswer = Observable<QuestionAnswer>.zip([getQuestionAnswerListRef(for: userId, before: artworkId)
흠 제가 이해한 대로면, observable array인 Observable<[QuestionAnswer]>에 Observable<QuestionAnswer>을 바로 merge시킬 수 없어서 Observable<[QuestionAnswer]>의 형태로 변환시키면서 병합하는 zip operator를 사용했습니다.

2022-11-25 07:19 UTC, SH0123 commented on Gom4ziz/Source/Data/Repository/FirebaseQuestionAnswerRepository.swift
> +    private func getQuestionAnswerListRef(for userId: String, before artworkId: Int) -> DocumentReference {
[질문]
혹시 이 부분은 questionAnswerList의 ref를 받아오는게 아니라 questionAnswer의 ref를 받아오는곳 아니에요?

2022-11-25 07:55 UTC, imparang commented on Gom4ziz/Source/Data/Repository/FirebaseQuestionAnswerRepository.swift
> +    private func getQuestionAnswerListRef(for userId: String, before artworkId: Int) -> DocumentReference {
저도 reference 자체는 questionAnswer를 가져오는 것 같아요.
`fetchQuestionAnswerList`는 그대로 가지면 될 거 같아요.
그래서 `getQuestionAnswer(of artworkId: Int, _ userId: String)`으로 바꾸면 어떨까요?

2022-11-25 08:01 UTC, imparang approved these changes
수고하셨습니다.

2022-11-25 08:01 UTC, imparang commented on Gom4ziz/Source/Data/Repository/FirebaseQuestionAnswerRepository.swift
> +        return Observable.zip(questionAnswerObservableList) { $0 }
지금 상황에선 zip도 괜찮은거 같네요.

2022-11-25 08:03 UTC, imparang commented on Gom4ziz/Source/Data/Repository/FirebaseQuestionAnswerRepository.swift
> +            returnQuestionAnswer = returnQuestionAnswer.concat(questionAnswer)
[질문]
merge 한 후 toArray를 호출하면 Single을 반환하더라고요. 
Observable로 반환하려고 `zip`이나 `combineLatest`를 사용한 부분인데 보통 어떻게 하나요? 
궁금하네요.

2022-11-25 08:20 UTC, rriver2 commented
코드리뷰를 확인한 후 다른 로직으로 짜기 위해서 @imparang 와 의논하면서, 수정한 후 [f1cb459](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/111/commits/f1cb459882c3b4caaa8197977d30c78f23baa51d) 새 commit을 날렸습니다. 확인부탁드립니다. 
@SH0123 @HoJongE

2022-11-25 08:24 UTC, rriver2 commented on Gom4ziz/Source/Data/Repository/FirebaseQuestionAnswerRepository.swift
> +        return Observable.zip(questionAnswerObservableList) { $0 }
[[RxSwift - combineLatest(), zip() 에 대해서 알아보자.](https://rhammer.tistory.com/311)](https://rhammer.tistory.com/311) 해당 문서를 읽어봤는데,
지금 상황에서는 combineLatest든 zip이든 상관 없을 거 같은데, zip으로 하는게 가독성이 좋을 것 같아 zip으로 바꿨습니다!

### combineLatest
<img width="646" alt="스크린샷 2022-11-25 오후 5 24 24" src="https://user-images.githubusercontent.com/82457928/203934884-ff279bb7-994d-4665-a21c-e47b00cd0d60.png">

### zip
<img width="637" alt="스크린샷 2022-11-25 오후 5 24 11" src="https://user-images.githubusercontent.com/82457928/203934871-e2ffc466-a88f-45de-812b-146a81b0b437.png">

2022-11-25 08:28 UTC, rriver2 commented on Gom4ziz/Source/Data/Repository/FirebaseQuestionAnswerRepository.swift
> +            let questionAnswer = Observable<QuestionAnswer>.zip([getQuestionAnswerListRef(for: userId, before: artworkId)
흠 제가 이해한 대로면, observable array인 Observable<[QuestionAnswer]>에 Observable<QuestionAnswer>을 바로 merge시킬 수 없어서 Observable<[QuestionAnswer]>의 형태로 변환시키면서 병합할 수 있는 zip operator를 사용했습니다.

2022-11-25 08:48 UTC, yungahui commented
멋찌군요 리버 🌊

2022-11-25 08:53 UTC, SH0123 commented on Gom4ziz/Source/Data/Repository/FirebaseQuestionAnswerRepository.swift
> +            returnQuestionAnswer = returnQuestionAnswer.concat(questionAnswer)
merge를 하고 toArray를 해서 Single을 반환하는 예시 참고용
https://stackoverflow.com/questions/35206671/how-do-i-create-an-observable-of-an-array-from-an-array-of-observables

저도 어떤 방식을 많이 쓰는지 궁금하네요

2022-11-25 09:01 UTC, SH0123 commented on Gom4ziz/Source/Constants/CollectionName.swift
> +    }
[질문]
제가 찾아봤을 때 zip은 최대 8개의 observable을 받을 수 있는 것 까지 구현이 되어있는 것 같은데, 혹시 더 많이 받을 수 있나용..? 궁금하네요 ㅎㅎ
그리고 zip으로 받게되면 array가 아닌 tuple 형태를 반환하는 것 같아요 ..! 아니라면 틀린부분 알려주시면 감사하겠습니다 ㅎㅎ 

그나저나 리버... 아주 고민이 많이 되는 부분을 맡았군요 ... ㅠㅠ 이런부분 잘 남겨두면 좋겠네요 ~ 덕분에 저도 고민 많이해보고 공부해봅니다

2022-11-25 11:19 UTC, HoJongE approved these changes
고생하셨습니다!!

2022-11-25 11:19 UTC, HoJongE commented on Gom4ziz/Source/Data/Repository/FirebaseQuestionAnswerRepository.swift
> +            questionAnswerObservableList.append(getQuestionAnswerRef(for: userId, before: i)
[사소한 의견]

수고하셨습니다!

for 문으로 배열을 돌면서 옵저버블을 추가하기보단, 

artworkId 배열에 map 함수를 적용해서 옵저버블 배열을 만들면 훨씬 깔끔할 것 같아요!!
```suggestion
[1...artworkId].map { getObservable() }
```

2022-11-26 02:27 UTC, rriver2 commented on Gom4ziz/Source/Constants/CollectionName.swift
> +    }
@SH0123 혹시 어디서 글을 보셨는지 링크 남겨주실 수 있나요 ? 
저는 9개까지 받을 수 있다는 내용의 [블로그](https://yesiamnahee.tistory.com/159)는 이것만 찾았었는데, [공문](https://reactivex.io/documentation/operators/zip.html)이나 다른 신뢰할만한 링크가 안 달려있더라구요 ...! 
그리고 "zip으로 받게되면 array가 아닌 tuple 형태를 반환하는 것"에 대한 글은 못 찾았어요 ㅠㅠ

+) 
혹시나 싶은 마음에 함수를 가데이터로 돌려서 확인해보니까 문제가 없는 것 같아요 ..!
```
    func fetchQuestionAnswerList(for userId: String, before artworkId: Int) -> Observable<[QuestionAnswer]> {
        var questionAnswerObservableList: [Observable<QuestionAnswer>] = []
        for i in 1...100 {
            questionAnswerObservableList.append(Observable.of(QuestionAnswer(questionAnswer: "\(i )///", timeStamp: 0, uid: "\(i)")))
        }
        return Observable.zip(questionAnswerObservableList)
    }
```
<img width="766" alt="스크린샷 2022-11-26 오전 11 23 44" src="https://user-images.githubusercontent.com/82457928/204068791-b4d84d37-ba21-4fbd-b4ed-94cc82010bd9.png">

2022-11-26 02:36 UTC, rriver2 commented on Gom4ziz/Source/Data/Repository/FirebaseQuestionAnswerRepository.swift
> +            questionAnswerObservableList.append(getQuestionAnswerRef(for: userId, before: i)
저도 사실 처음에는 이 코드로 짰었는데,
map 안에서 error가 발생되면, 성공한 애들도 다 같이 날라가 버리더라구요.. closure 관련 issue인 것 같은데.. 잘 모르겠어서 우선 위와 같이 구현했습니다.. closure 공부해서 다시 try 해보겠습니다! 제안 감사합니다 ☺️
error 예시) 
artworkId 값이 DB에 있는 Id 값보다 클 경우
```
        let questionAnswerObservableList = Array(1...artworkId).map { i in
            getQuestionAnswerRef(for: userId, before: i)
                .rx
                .decodable(as: QuestionAnswer.self)
        }
```

2022-11-26 02:37 UTC, merged

2022-11-26 10:40 UTC, SH0123 commented on Gom4ziz/Source/Constants/CollectionName.swift
> +    }
오 가데이터로 돌려서 문제 없으면 괜찮은 것 같아요 ㅎㅎ 
zip 정의되어 있는 부분을 보다보니 tuple로 되어있었어서 우려되어 한 말인데 검증해봤으니 괜찮은 것 같아요 ㅎㅎ
아래에 찾아봤던 내용 놔뒀습니당
@rriver2 
<img width="617" alt="스크린샷 2022-11-26 오후 7 30 37" src="https://user-images.githubusercontent.com/26588989/204084572-22fe8e1d-8749-4e12-9229-eda04b205d2e.png">

2022-11-27 01:14 UTC, rriver2 commented on Gom4ziz/Source/Constants/CollectionName.swift
> +    }
감사합니다 레몬 ! :) 깃헙 읽는 것도 연구를 해봐야겠네요 하나 배워갑니다 감사합니다 ☺️