[Feature] #125: 감상 기록 화면에서 데이터 요청 결과에 따른 UI를 구현했습니다.
DeveloperAcademy-POSTECH/MacC_Team_Beartear pull request #137
Opened 2022-11-29 04:30 UTC by imparang

## Close Issues
- Pull Request와 관련된 Issue가 있다면 나열합니다.
🔒 Close #125

## 작업 내용 (Content)
- 감상 기록 화면 전반적인 로직입니다.
- <img width="1018" alt="Screenshot 2022-11-29 at 13 09 30" src="https://user-images.githubusercontent.com/59136391/204439058-b9ca39a6-aa16-41ff-afc0-79088d65b68d.png">

- 유저가 감상 기록으로 들어가면 DB에서 ArtworkDescription, Highlight, ArtworkReview를 불러오고, 
데이터가 요청되는 동안은 `LoadingView`를 보여주고, 데이터 요청이 성공하면 View를 잘 보여주고, 실패하면 `ErrorView`를 보여줄 수 있게 했습니다.
- 데이터 요청이 실패하여 ErrorView가 나타내게 되면, `탭하여 다시 시도`버튼을 눌러 데이터를 다시 요청할 수 있습니다.
- 이 과정을 편하게 사용할 수 있도록 UIViewControler+Extension으로 새로 만들었습니다.
<div style="display: flex; justify-content: center; align-items: center">
<img width="157" alt="Screenshot 2022-11-29 at 13 16 51" src="https://user-images.githubusercontent.com/59136391/204439041-0f9d93f0-c907-4218-ac70-6a4a5373aeb3.png">
<img width="224" alt="Screenshot 2022-11-29 at 13 18 27" src="https://user-images.githubusercontent.com/59136391/204438185-73e88498-ba35-47ec-8fa0-ab8ac5740e03.png">
</div>

- @HoJongE 가 제안해준 ViewModel에서 DAO를 DTO로 변환하고, 이를 ViewController에서 사용할 수 있도록 리팩토링했습니다.

## Review points
- 데이터 요청의 결과에 따른 처리를 위해 `isLoading` 이라는 property observer를 만들었습니다.

## 기타 사항 (Etc)
- UIViewControler+Extension을 만들었는데 이게 적절한지 모르겠네요.
- 메인화면에서 Artwork, QuestionAnswer 정보가 있어서 ViewModel에서 변환한 DTO에 해당 값들을 따로 넣지 않았는데 맞는지 모르겠습니다.

## 관련 사진 gif 및 (Optional)

## References (Optional)
- 참고한 사이트나 정리한 wiki 링크를 넣어주세요
- [링크이름](링크)

2022-11-29 04:54 UTC, SH0123 approved these changes
굳굳

2022-11-29 04:54 UTC, SH0123 commented on Gom4ziz/Source/Extension/UIViewController+Loadble.swift
> +            loadingView.centerYAnchor.constraint(equalTo: self.view.centerYAnchor),
[질문]
아래 네개의 나머지 제약에서 모든 제약을 다 줬다고 생각하는데, xy축의 제약은 왜 줬는지 궁금합니다

2022-11-29 05:32 UTC, imparang commented on Gom4ziz/Source/Extension/UIViewController+Loadble.swift
> +            loadingView.centerYAnchor.constraint(equalTo: self.view.centerYAnchor),
아 아마 loadingview 를 따로 만들기 전에 잡아뒀던 제약이 남아있네요. 제거하겠슴강

2022-11-29 07:16 UTC, HoJongE requested changes
고생하셨씁니다.
근데 각 데이터들의 실패, 성공 여부 케이스를 모두 고려한 코드를 짜다보니까 굉장히 복잡한 것 같아요. zip과 View를 위한 Model을 쓰는 의미가 없어지는 것 같습니다.

2022-11-29 07:16 UTC, HoJongE commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
> +    }
[질문]
ViewModel에 Loadable<ViewModelMapper> 라는 relay가 있는데, 왜 이 프로퍼티들이 필요한가요?

2022-11-29 07:16 UTC, HoJongE commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
> +    private var highlightsError = false
[수정 필수]
Loadable의 failed 상태로 에러 상태를 다 표현할 수 있는데, 이 프로퍼티들은 필요없는 것 같아요

2022-11-29 07:16 UTC, HoJongE commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
> +    }
[수정 고려]
지금 이 모든 코드가, 리뷰를 불러오다가 실패하거나, 설명을 불러오다가 실패하거나, 하이라이트를 불러오다가 실패하거나 등등의 케이스를 모두 처리하려고 나온 것 같은데요. 이러면 zip으로 굳이 하나로 합치기 보다는, 그냥 원래 DAO를 하나하나 전부 relay로 가지고 있는게 나은 것 같네요. 
이렇게 각 데이터를 따로 처리할거면, zip으로 굳이 합칠 필요가 없을 것 같습니다.

2022-11-29 07:16 UTC, HoJongE commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
> +    }
어차피 요청실패 확률도 엄청 낮은데, 그냥 하나라도 에러 뜨면 전부 다시 불러오게 하면 어떨까요?

2022-11-29 07:16 UTC, HoJongE commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
> +    }
모든 케이스를 고려하니까 코드가 너무 복잡한 것 같아요.

2022-11-29 07:16 UTC, HoJongE commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewModel.swift
>  import RxCocoa
[질문]
Cocoa대신 Relay를 import하는게 낫지 않나요?

2022-11-29 12:45 UTC, imparang commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
> +    }
전에 코드랑 섞인채로 그냥 해버렸네요 ㅜ.
수정했습니다.

2022-11-29 12:48 UTC, imparang commented on Gom4ziz/Source/Presenter/Component/LoadingView.swift
> +final class LoadingView: BaseAutoLayoutUIView {
지금은 UIActivityIndicatorView인데 나중에 로티가 들어올 것을 생각해서 따로 뷰를 만들었어요.

2022-11-29 12:48 UTC, HoJongE commented on Gom4ziz/Source/Presenter/Component/LoadingView.swift
> +final class LoadingView: BaseAutoLayoutUIView {
오켕케이 납득했씁니다.

2022-11-29 12:49 UTC, imparang commented on Gom4ziz/Source/Extension/UIViewController+Loadble.swift
> +        errorView.removeFromSuperview()
> [사소한 의견] 바깥에서 ErrorView에 대한 참조를 유지할 필요 없게, view의 자식뷰를 순회하면서 타입 캐스팅해서, ErrorView이면 removeFromSuperView하게 하면 어떨까요?
> 
> ```swift
> // 수도 코드
> for 자식뷰 in self.자식뷰리스트 {
>   if 자식뷰 is ErrorView {
>     자식뷰.removeFromSuperView()
>   }
> }
> ```

처음에 이생각을 했는데, 서브뷰가 많을 경우 순회를 하는게 맞을까 라는 생각에서 지금 방식으로 바꿨습니다.

2022-11-29 12:50 UTC, imparang commented on Gom4ziz/Source/Extension/UIViewController+Loadble.swift
> +    func setUpErrorView(_ errorView: ErrorView) {
같은 이유에서 처음에는 내부에서 만들고 제거하는 방식으로 했다가 서브뷰 순회 없이 제거하고 싶어서 방법을 찾다가 찾지 못해서 이 방식을 사용했습니다.

2022-11-29 12:51 UTC, imparang commented on Gom4ziz/Source/Extension/UIViewController+Loadble.swift
> +        errorView.removeFromSuperview()
> [사소한 의견] 바깥에서 ErrorView에 대한 참조를 유지할 필요 없게, view의 자식뷰를 순회하면서 타입 캐스팅해서, ErrorView이면 removeFromSuperView하게 하면 어떨까요?
> 
> ```swift
> // 수도 코드
> for 자식뷰 in self.자식뷰리스트 {
>   if 자식뷰 is ErrorView {
>     자식뷰.removeFromSuperView()
>   }
> }
> ```

그냥 이렇게 할까요?

2022-11-29 12:55 UTC, imparang commented on Gom4ziz/Source/Extension/UIViewController+Loadble.swift
> +        errorView.removeFromSuperview()
ErrorView 내부 retryButton 을 누르면 removeFromSuperView() 을 호출하도록 바꿨습니다.

2022-11-29 12:55 UTC, imparang commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
> +            .exposure(0.3)
궁금해서 넣어보다가 삭제를 깜빡했네요.
수정하게습니당

2022-11-29 13:31 UTC, imparang commented on Gom4ziz/Source/Extension/UIViewController+Loadble.swift
> +            loadingView.centerYAnchor.constraint(equalTo: self.view.centerYAnchor),
[171a7bd](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/137/commits/171a7bdf96c6ebff17d7991d9bb7c0309a4aa3a0)

2022-11-29 13:31 UTC, imparang commented on Gom4ziz/Source/Presenter/Component/LoadingView.swift
> +        activityIndicator.center = self.center
[171a7bd](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/137/commits/171a7bdf96c6ebff17d7991d9bb7c0309a4aa3a0)

2022-11-29 13:31 UTC, imparang commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
> +            .exposure(0.3)
[171a7bd](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/137/commits/171a7bdf96c6ebff17d7991d9bb7c0309a4aa3a0)

2022-11-29 13:31 UTC, imparang commented on Gom4ziz/Source/Extension/UIViewController+Loadble.swift
> +    func setUpErrorView(_ errorView: ErrorView) {
[d0298f6](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/137/commits/d0298f62fb3a8ee61f81a7f21b3dc5d5b452ae5a)

2022-11-29 13:31 UTC, imparang commented on Gom4ziz/Source/Extension/UIViewController+Loadble.swift
> +    func setUpLoadingView(_ loadingView: LoadingView) {
[d0298f6](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/137/commits/d0298f62fb3a8ee61f81a7f21b3dc5d5b452ae5a)

2022-11-29 13:31 UTC, imparang commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
> +    }
[7c55da5](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/137/commits/7c55da5cffddc8ef5f953bd089586b38990fdf8a)

2022-11-29 13:31 UTC, imparang commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
> +    private var highlightsError = false
[7c55da5](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/137/commits/7c55da5cffddc8ef5f953bd089586b38990fdf8a)

2022-11-29 13:31 UTC, imparang commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
> +    }
[7c55da5](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/137/commits/7c55da5cffddc8ef5f953bd089586b38990fdf8a)

2022-11-29 13:53 UTC, HoJongE requested changes
순환 참조를 고려하면 좋을 것 같아요

2022-11-29 13:53 UTC, HoJongE commented on Gom4ziz/Source/Extension/UIViewController+Loadble.swift
> +            subView.removeFromSuperview()
[질문]
for문에서 where 사용은 처음 보네요 ㄷㄷ 혹시 이러면 어떤 방식으로 순회하나요?

2022-11-29 13:53 UTC, HoJongE commented on Gom4ziz/Source/Presenter/Component/ErrorView.swift
[사소한 의견]
함수에 private vs extension에 private
이런 경우 extension 내부에 함수가 하나 밖에 없지만, 스타일 통일을 위해선 extension에 붙이는게 좋을 것 같다는 의견을 남겨봅니다!

2022-11-29 13:53 UTC, HoJongE commented on Gom4ziz/Source/Extension/UIViewController+Loadble.swift
> +            subView.removeFromSuperview()
[사소한 의견]
밑에 tag보면서 생각한건데, 여기서도 LoadingView에 태그를 붙여서 찾으면 안되나요?

2022-11-29 13:53 UTC, HoJongE commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewModel.swift
> +        .observe(on: MainScheduler.instance)
[사소한 의견]
VIewModel 쪽에서 Scheduler를 지정해주기 보다는, 관찰하는 쪽에서 asDriver로 변경하는 편이 낫다고 생각합니다!

2022-11-29 13:53 UTC, HoJongE commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
> +        editButton.tintColor = .black
[수정 고려]
이 부분 navigationBar의 barTintColor를 바꾸면, navigation Item들 틴트도 모두 바뀌는 것 같더라구요 ㅎㅎ..

2022-11-29 13:53 UTC, HoJongE commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
> +            }
[수정 필수]
myFeedViewModelMapper는 Relay고, 이 부분에서 self를 참조하므로 순환참조가 일어날 것 같아요.
또한 map은 단순히 데이터를 변경할 뿐, 보통 상태 변경에는 어울리지 않는 연산자에요. 따라서 UI 상태를 변경하는 코드는, do 연산자에서 진행하는게 어떨까요?

2022-11-29 13:53 UTC, HoJongE commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
> +            }
[수정 필수]
이 부분도 순환참조가 일어날 것 같네요.

2022-11-29 13:53 UTC, HoJongE commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
> +         myFeedViewModelDTO: MyFeedViewModelMapper? = nil) {
[사소한 의견]
Mapper는 데이터를 변환하는 역할을 할 것 같고, View를 위한 Model 에는 적절하지 않은 네이밍이라는 생각을 해봅니다

2022-11-30 02:02 UTC, imparang commented on Gom4ziz/Source/Extension/UIViewController+Loadble.swift
> +            subView.removeFromSuperview()
> [질문]
> for문에서 where 사용은 처음 보네요 ㄷㄷ 혹시 이러면 어떤 방식으로 순회하나요?

if subView is LoadingView 랑 같아요.

2022-11-30 02:02 UTC, imparang commented on Gom4ziz/Source/Extension/UIViewController+Loadble.swift
> +            subView.removeFromSuperview()
> [사소한 의견]
> 밑에 tag보면서 생각한건데, 여기서도 LoadingView에 태그를 붙여서 찾으면 안되나요?

음 에러뷰하면서 생각났는데 여기도 적용해볼게요.

2022-11-30 02:03 UTC, imparang commented on Gom4ziz/Source/Presenter/Component/ErrorView.swift
확인입니다.

2022-11-30 02:26 UTC, imparang commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
> +            }
[위의 코멘트](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/137#discussion_r1034768993)
에서 든 생각인데 viewController에서 asDriver() 해주고 drive() 내부에서 해당 로직을 다 처리해줘도 괜찮나요?

2022-11-30 02:29 UTC, imparang commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedView.swift
> +         myFeedViewModelDTO: MyFeedViewModelMapper? = nil) {
[b204664](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/137/commits/b20466494d02340a47c305a92b4ad1f943db1a15)
Mapper -> DTO로 변경했습니다.

2022-11-30 02:29 UTC, imparang commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
> +        editButton.tintColor = .black
[b204664](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/137/commits/b20466494d02340a47c305a92b4ad1f943db1a15)
적용완료

2022-11-30 02:30 UTC, imparang commented on Gom4ziz/Source/Presenter/Component/ErrorView.swift
[37ca2f0](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/137/commits/37ca2f01223ee4e64d7fdc3f5c6ccf7c186104ca)

2022-11-30 02:32 UTC, imparang commented on Gom4ziz/Source/Extension/UIViewController+Loadble.swift
> +            subView.removeFromSuperview()
[bd8ae83](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/137/commits/bd8ae83754cba8259d4e27ecc5466a3ce43b2801)

2022-11-30 02:33 UTC, imparang commented on Gom4ziz/Source/Presenter/MyFeed/MyFeedViewController.swift
> +            }
[b204664](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/137/commits/b20466494d02340a47c305a92b4ad1f943db1a15)

2022-11-30 04:23 UTC, HoJongE approved these changes
수고하셨습니다~~

2022-11-30 05:07 UTC, merged