[Feature]: Loading시 보여주는 TempSkeletonImageViewController 구현
DeveloperAcademy-POSTECH/MacC_Team_Beartear pull request #176
Opened 2022-12-02 13:51 UTC by rriver2

## Close Issues
- Pull Request와 관련된 Issue가 있다면 나열합니다.
🔒 Close #173 

## 작업 내용 (Content)
- 작업한 내용을 나열 후 설명
- imageName 변수를 받는 TempSkeletonImageViewController를 구현했습니다. issue에서 작성한 대로, 시간이 없어서 일단 image로 Skeleton UI를 구현했습니다.

## Review points
- 리뷰어가 중점적으로 리뷰해줬으면 하는 포인트

## 기타 사항 (Etc)
- 작업하면서 고민이 되었던 부분이나 질문 사항 등
- 하단의 코드에서 .notRequested, .isLoading 부분이 user 데이터를 불러오는 걸 failed하기 전, 후 둘 다 들어가다보니까 
<img width="1009" alt="스크린샷 2022-12-02 오후 10 47 31" src="https://user-images.githubusercontent.com/82457928/205307068-7a8b25a5-a019-46cd-ac0f-dbfbdf6570e6.png">

아래 영상과 같이 작동하게 됩니다.... 이를 분기할 수 있는 방법이 있을까요 ?
![ezgif com-gif-maker](https://user-images.githubusercontent.com/82457928/205307763-b015221b-0501-49ba-b383-e1c2f420e9b9.gif)

## 관련 사진 gif 및 (Optional)

## References (Optional)
- 참고한 사이트나 정리한 wiki 링크를 넣어주세요

2022-12-02 14:03 UTC, SH0123 reviewed
수고하셨습니다 ~

2022-12-02 14:03 UTC, SH0123 commented on Gom4ziz/Source/System/SceneDelegate.swift
> +                            self.changeRootViewController(TempSkeletonImageViewController(imageName: ImageName.mainLoading))
호종이가 이슈에서도 언급했지만 tempSkelton은 mainViewController에 view로 주입해줘야할 것 같습니다.
그리고 sceneDelegate에서 userObservable 상태에는 종속적이면 안된다는 생각을 했습니다! 
메인의 tempSkelton은 유저가 loaded 되었을 때 mainViewController로 넘어가게 되고, 그 상황에서 tableView에 들어가는 내용들과 artwork question이 loading 상태일 때 나타나는 뷰라고 생각됩니다.

저도 자세한 부분은 계속 고민하고 있어서 다른분들의 조언도 들어봅시다

2022-12-03 05:58 UTC, HoJongE requested changes
고생하셨습니다~~ ViewController 대신에, subView로 추가하는게 맞는 방식인 것 같아요.

2022-12-03 05:58 UTC, HoJongE commented on Gom4ziz/Source/Presenter/Main/TempSkeletonImageView.swift
> +final class TempSkeletonImageViewController: UIViewController {
[수정 고려]

저도 로딩 스켈레톤 UI는 MainViewController에서 데이터를 로딩할 때 나올 화면이지, 아예 다른 뷰컨트롤러가 나오는 건 아닌 것 같아요. 
그냥 화면을 꽉 채워버리는 UIView로 구현해서, MainViewController의 view의 subView로 추가하는 방식으로 구현하는게 좋을 것 같아요.

```swift
switch 작품리스트 릴레이 {
케이스 이즈로딩: 스켈레톤 UI를 subView로 추가한다 (화면을 다 덮게)
케이스 로딩완료: 스켈레톤 UI를 subView에서 제거한다.
}
```

2022-12-03 05:58 UTC, HoJongE commented on Gom4ziz/Source/System/SceneDelegate.swift
> +                            self.changeRootViewController(TempSkeletonImageViewController(imageName: ImageName.mainLoading))
이ㅂ 부분은 저도 상효보이의 의견에 동의합니다.

2022-12-03 14:00 UTC, closed without merging