feat: KaKao Login, Logout, unLink testUI 작성
DeveloperAcademy-POSTECH/MacC_Team_Beartear pull request #28
Opened 2022-10-25 08:17 UTC by rriver2

## Close Issues
- Pull Request와 관련된 Issue가 있다면 나열합니다.
🔒 Close #13

## 작업 내용 (Content)
- [x] 카카오 네이티브 앱 만들기
- [x] [카카오 로그인 모듈 설치](https://developers.kakao.com/docs/latest/ko/kakaologin/ios#before-you-begin-module)
- [x] 테스트 UI (로그인 후 계정 정보 표시, 로그아웃, 탈퇴)
- [x] 이전에 로그인 한 유저면 계정 정보 표시 UI
- [x] ViewController, ViewModel 역할 나누기
- [x] 호종이 카카오 네이티브 앱으로 변경하기 (제가 하나 만들어서 작업 중이었습니다...)

## Review points
- 리뷰어가 중점적으로 리뷰해줬으면 하는 포인트
[호종이 리뷰](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/28)보고 ViewModel에서 도메인 로직을 구현하지 않고 Usecase(Manager)에 필요한 함수를 호출하도록 구조를 수정했습니다.
<img width="869" alt="스크린샷 2022-10-28 오전 9 51 55" src="https://user-images.githubusercontent.com/82457928/198424171-6160d890-ad13-4fb6-8c00-b48ded00a54d.png">

## 기타 사항 (Etc)
- 작업하면서 고민이 되었던 부분이나 질문 사항 등
- LoginManagerProtocol 프로퍼티에 다음과 같은 변수를 필요로 한다고 코드를 짜서 KakaoLoginManager에 해당 프로퍼티가 있는데, KakaoLoginManager가 아닌 ViewModel에 해당 값이 있어야 하는 건지 잘 모르겠습니다. 

```
    var userInfo: PublishRelay<UserInfo> { get }
    var loginstatus: PublishRelay<Loginstatus> { get }
```
- ~~@HoJongE 제가 카카오 네이티브 앱을 만들었었는데, 호종이께서 네이티브 앱을 만들어 팀원을 초대하셨더라구요! 그걸로 이동하겠습니다! 확인하시면 댓글 남겨주세요~~ -> 네이티브 앱 호종이 껄로 이동 후에 [세부 내용 설정](https://developers.kakao.com/console/app)했습니다.
- ~~로그인 시 사용자에게 Client가 "닉네임과 프로필 사진" 접근을 허용할 것인지 물어봅니다. 이 접근 허용 필수 선택으로 변경할까요?~~ -> 우선 선택 허용으로 두겠습니다.

## 관련 사진 gif 및 (Optional)
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/82457928/197446734-a4e9f022-e794-472a-9912-4374c825d3ab.gif)
- 1. 회원가입 시 사용자에게 "닉네임과 프로필 사진"의 접근 허용 구함 
- 2. 회원 탈퇴시 access token 날림 + 다시 회원가입 해야 함
- 3. 로그아웃 시 access token 날림 + 다시 로그인 해야 함
- 4. 로그인 후 앱 껐다 켜도 Client가 access token을 가지고 있기 때문에 "닉네임과 프로필 사진"에 접근 가능

## References (Optional)
- 참고한 사이트나 정리한 wiki 링크를 넣어주세요
- [OAuth2 개념에 대해 wiki에 정리해 뒀습니다.](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/discussions/22)
- [카카오 로그인 및 회원가입 등 개발자 문서](https://developers.kakao.com/docs/latest/ko/kakaologin/ios)

2022-10-25 08:21 UTC, rriver2 commented
[이전 PR](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/23)이 라이브러리를 동시에 import하면서 rebase하는 과정에서 project.pbxproj이 많이 꼬였습니다. 문제를 해결하고자 노력을 하였으나 시간이 너무 많이 소요되었고, 수정한 파일이 몇 개 없는 점을 고려해서 새로 작업하는 게 빠를 거라는 판단을 내렸습니다. 도움 주신 호종이 감사합니다 :)

### 라이브러리를 import할 때 slack에서 공지를 먼저 하는 문화를 자리잡으면 좋을 것 같습니다

2022-10-25 10:07 UTC, SH0123 commented
> [이전 PR](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/23)이 라이브러리를 동시에 import하면서 rebase하는 과정에서 project.pbxproj이 많이 꼬였습니다. 문제를 해결하고자 노력을 하였으나 시간이 너무 많이 소요되었고, 수정한 파일이 몇 개 없는 점을 고려해서 새로 작업하는 게 빠를 거라는 판단을 내렸습니다. 도움 주신 호종이 감사합니다 :)
> 
> ### 라이브러리를 import할 때 slack에서 공지를 먼저 하는 문화를 자리잡으면 좋을 것 같습니다

asset은 모두가 사용하는 것이기 때문에 추가할 때 기존의 작업에서 하지 않고, 새로운 브랜치에서 작업하면 좋듯이 라이브러리를 추가할 때도 따로 하나의 브랜치에서 진행하고 slack에서 공지를 하면 더욱 좋겠군요!!

2022-10-25 14:07 UTC, HoJongE commented on Gom4ziz/Gom4ziz/System/SceneDelegate.swift
>      }
제가 지금 딥링크를 처리하려고 Deeplink Handler 객체를 생성했는데, 다음 pr 때 다 같이 합쳐서 리팩토링하면 되겠군요!!

2022-10-26 08:28 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewController.swift
> +            .disposed(by: disposeBag)
imageURL이 nil일 때 UIImage()를 testView.userImageView에 대입하고 싶은데, 해당 코드를 구현하지 못해서,..
아래 switch 문에서 isHidden을 false/ true로 변경했습니다.

관련해서 힌트나 조언 부탁드립니다..! 🥲

2022-10-26 08:28 UTC, rriver2 commented on Gom4ziz/Gom4ziz/System/SceneDelegate.swift
>      }
요홍 그러면 제꺼 먼저 머지 한 후에 작업하시면 되는 걸까요 ?

2022-10-26 10:58 UTC, HoJongE requested changes
고생하셨습니다!!
조금만 리팩토링하면 좋을 것 같아요!
근데 확실히 저도 개발초기엔 이런 내용이 너무 어려웠어서 궁금하시면 도움을 요청해주세요

2022-10-26 10:58 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginView.swift
> +        unLinkButton.translatesAutoresizingMaskIntoConstraints = false
[사소한 의견] 
addSubView 와 translateAuto 도 UI Componenet 를 생성하는 클로저에서 실행하면 어떨까요?

2022-10-26 10:58 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewModel.swift
> +
[수정필수]
https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/20

여기 마지막에 에코가 제안해준 것처럼, 임포트 하는 데 저 규칙을 따르면 좋을 것 같습니다!

2022-10-26 11:05 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewModel.swift
> +    }
> [수정 필수]
> 다음 함수 이전 함수 사이의 공간을 만들어주세요

swiftLint 수정이 필요할 듯 합니다 ! 이번 codereview pr에 변경해서 push 하겠습니다 !

2022-10-26 11:07 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Domain/Model/UserInfo.swift
> +    let imageURL: URL?
> [질문] 저희 프로필사진이 근데 디자인상에서 아직 안 들어가있지 않나요??
<img width="175" alt="스크린샷 2022-10-26 오후 8 07 29" src="https://user-images.githubusercontent.com/82457928/198010921-e15681dd-d47e-4d73-a1f0-75bdf6a4b37c.png">
프로필 사진이 있을 거 같아서 하는 김에 불러왔습니다. 디자이너분께 한번 여쭤보겠습니다!

2022-10-26 11:08 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewController.swift
> +            .disposed(by: disposeBag)
감사합니다 !

2022-10-26 12:12 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginView.swift
> +        unLinkButton.translatesAutoresizingMaskIntoConstraints = false
동의합니다.

2022-10-26 12:13 UTC, imparang commented on Gom4ziz/Gom4ziz/Domain/Model/UserInfo.swift
> +    let imageURL: URL?
요거 바꾸면 다른 부분도 바꿔야할 텐데 화이팅입니다!

2022-10-27 05:20 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Domain/Model/UserInfo.swift
> +    let imageURL: URL?
디자이너분께 여쭤본 결과 프로필 사진 넣어두기로 했습니다 :) !

2022-10-28 00:33 UTC, rriver2 commented on Gom4ziz/Gom4ziz/System/SceneDelegate.swift
>      }
[해당 부분](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/28/files#diff-867efed63e7babd99448d7d1b24b08c2b5ba166b4f7114d7425e36cb8b8c115e:~:text=%7D-,func%20scene(_%20scene%3A%20UIScene%2C%20openURLContexts%20URLContexts%3A%20Set,%7D,-func%20sceneDidDisconnect() 수정했습니다 확인해주세요 :)

2022-10-28 00:38 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginView.swift
> +        unLinkButton.translatesAutoresizingMaskIntoConstraints = false
[해당 부분](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/28/files#diff-db325d30242288e0af2aed802944ac65719b234f844d1344145a235f57444f74:~:text=%3A%20UIView%20%7B-,private%20(set)%20lazy%20var%20loginButton%3A%20UIButton%20%3D%20%7B,%7D,-%23if%20DEBUG) 수정했습니다

2022-10-28 00:40 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewModel.swift
> +
[a1812e8](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/28/commits/a1812e8f142b371718d62090ff3de6cb9d2e4335) 수정했습니다 !

2022-10-28 00:40 UTC, rriver2 commented on Gom4ziz/Gom4ziz/System/SceneDelegate.swift
[a1812e8](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/28/commits/a1812e8f142b371718d62090ff3de6cb9d2e4335) 수정했습니다 !

2022-10-28 00:40 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewModel.swift
> +    }
[a1812e8](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/28/commits/a1812e8f142b371718d62090ff3de6cb9d2e4335) 수정했습니다 ! 도움 주셔서 감사합니다 !

2022-10-28 10:51 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginView.swift
> +        unLinkButton.translatesAutoresizingMaskIntoConstraints = false
확인완료

2022-10-28 11:06 UTC, HoJongE approved these changes
수정 필수부분만 수정하시고 머지하시면 될 것 같아요~

2022-10-28 11:06 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewController.swift
> +import UIKit
여기도 위에서 알려준 대로 import 하기를 바래요!!

2022-10-28 11:06 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginView.swift
> +class KakaoLoginView: UIView {
[수정 필수]
더 이상 상속되지 않는 클래스라면 항상 final 을 붙여 주세요! 슬랙과 디스커션에 올린 메소드 디스패치 관련 내용과 연관있습니다.
method dynamic dispatch 를 static dispatch 로 바꿈으로써 런타임 성능을 향상.

2022-10-28 11:06 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/LoginManagerProtocol.swift
> +}
[수정 고려]
저 여기 한 가지 제안사항이 있어요. LoginStatus 가 유저의 로그인 상태를 나타내는데, login 되있다면 UserInfo가 존재한다는 소리잖아요.  따라서 연관값으로 UserInfo 타입을 가지고 있으면 어떨까요? 즉 로그인 상태와 로그인 데이터가 같이 존재하는거에요.

```suggestion
enum Loginstatus {
    case login(userInfo: UserInfo) // <- 로그인 상태일 땐, 유저인포를 같이 들고 있다. 즉 userInfo 라는 PublishRelay가 따로 필요없어짐
    case logout
    case unlink
}
```

2022-10-28 11:06 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewController.swift
> +    private func isTokenVailed() {
[수정 고려]
private extension이라서 private 지정자 선언이 필요없습니다

2022-10-30 05:55 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginManager.swift
> +import UIKit
공지를 제대로 안 읽었었네요.. 다음에는 더 주의하겠습니다 감사합니다 :)

2022-10-30 05:57 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/LoginManagerProtocol.swift
> +}
수정 제안 감사합니다 ! 이 부분은 후에 @SH0123 과 작업해서 올릴 때 수정해서 올리도록 하겠습니다 !

2022-10-30 06:23 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/LoginManagerProtocol.swift
> +}
확인했습니다~

2022-10-30 06:24 UTC, HoJongE approved these changes
머지하시면 될 것 같아요~~

2022-10-30 07:54 UTC, imparang requested changes
고생하셨습니다.
다만 코드의 일관성을 위해서 몇몇 부분 수정을 부탁드리겠습니다!

2022-10-30 07:54 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginManager.swift
> +    let userInfo: PublishRelay<UserInfo> = .init()
[질문]
Subject로 PublishRelay를 사용하신 이유가 있을까요?

2022-10-30 07:54 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewController.swift
> +                .disposed(by: self.disposeBag)
[수정필수]
다른 곳에서는 disposeBag만 하셨으니 이것도 self 빼주세용

2022-10-30 07:54 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/LoginManagerProtocol.swift
> +    var loginstatus: PublishRelay<Loginstatus> { get }
[질문]
여기도 마찬가지로 PublishRelay를 사용하신 이유가 무엇인가요?

2022-10-30 07:54 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewController.swift
> +                    print("토큰 유효성 체크 성공(필요 시 토큰 갱신됨)")
[고려]
debug가 목적인거라면 print문 말고 Logger를 만들어서 우리 모두 사용하는 것도 하나의 방법이겠네요.
https://ios-development.tistory.com/381
참고용입니다.

2022-10-30 07:54 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginManager.swift
> +                self.userInfo.accept(UserInfo(id: UUID().uuidString, name: "로그아웃 성공", imageURL: nil))
MockData 활용해주세용

2022-10-30 07:54 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginManager.swift
> +            .subscribe(onSuccess: { user in
강한순환참조 고려해주셔야할 것 같습니당

2022-10-30 07:54 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginManager.swift
> +    func unlink() {
[수정고려]
unlink로는 무슨의미인지 파악이 잘 되지 않네요.(회원 탈퇴같지 않다.) 다른 네이밍을 고려해보는 것도 좋을거 같습니당

2022-10-30 07:54 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewController.swift
> +                        self.testView.userImageView.isHidden = true
self 사용 통일성있게 해주세요.
위에는 사용안하셨으니 self 지워주세용.
만약 사용하신 이유가 있다면 말씀해주세요.

일단 저같은 경우는 상속받은 속성의 경우는 self를 붙여주고 직접 구현한 속성은 self를 붙이지 않습니다.
예를 들면
```
private extension PlansRoomListCell {
    
  func setup() {
        self.backgroundColor = .lightGray
        self.clipsToBounds = true
        self.layer.cornerRadius = 28
        self.addSubview(thumnailImage)
        self.addSubview(plansRoomInfoStackView)
   }

  func setthumnailImageConstraints() {
        NSLayoutConstraint.activate([
            thumnailImage.topAnchor.constraint(equalTo: self.topAnchor, constant: 10),
            thumnailImage.leadingAnchor.constraint(equalTo: self.leadingAnchor, constant: 10),
            thumnailImage.bottomAnchor.constraint(equalTo: self.bottomAnchor, constant: -10),
            thumnailImage.widthAnchor.constraint(equalToConstant: 110),
            thumnailImage.heightAnchor.constraint(equalToConstant: 110)
        ])
    }

//...
}  
```

2022-10-30 08:35 UTC, HoJongE commented
OAuth 방식의 로그인은 함수 호출하자마자 결과가 바로 오는게 아니라서 LoginManager 에서 Relay 혹은 completion handler 로 이벤트를 처리하는게 맞는 선택인 것 같아요!
그러나 ViewModel 에서 Manager 를 internal 로 외부에 공개하면 안 될 것 같아요. 대신 ViewModel 에도 Relay 나 Drive 를 하나 더 만들어서, Manager의 relay 에 변경이 생기면 그 값을 바로 viewModel 의 relay 로 방출해도 될 것 같아요 (bind 혹은 drive 를 통해)

2022-10-30 14:39 UTC, SH0123 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginView.swift
> +class KakaoLoginView: UIView {
슬랙과 디스커션에 올려놓으셨다고 했는데 못찾겠습니다
링크 부탁드려요 ~

2022-10-30 14:50 UTC, imparang commented
> OAuth 방식의 로그인은 함수 호출하자마자 결과가 바로 오는게 아니라서 LoginManager 에서 Relay 혹은 completion handler 로 이벤트를 처리하는게 맞는 선택인 것 같아요! 그러나 ViewModel 에서 Manager 를 internal 로 외부에 공개하면 안 될 것 같아요. 대신 ViewModel 에도 Relay 나 Drive 를 하나 더 만들어서, Manager의 relay 에 변경이 생기면 그 값을 바로 viewModel 의 relay 로 방출해도 될 것 같아요 (bind 혹은 drive 를 통해)

오호 그렇군요. 그러면 그런식으로 처리하는게 맞겠군요. 감사합니다! ho paper

2022-10-31 14:30 UTC, yungahui commented
아요 "닉네임과 프로필 사진" 접근 >>선택 허용<< 좋아유~~

2022-11-01 02:28 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginManager.swift
> +    let userInfo: PublishRelay<UserInfo> = .init()
~Subject는 .completed, .error의 이벤트가 발생하면 subscribe가 종료되는 반면에
~Relay는 .completed, .error를 발생하지 않기 때문에 Dispose되기 전까지 계속 작동합니다. 
따라서 UI Event에서 사용하기 적절하다고 공부했었습니다..! 

그리고 Relay에는 PublishRelay와 BehaviorRelay가 있는데, 
BehaviorSubject는 현재값을 알 수 있는 value 라는 프로퍼티를 가지고 있고, PublishRelay는 해당 프로퍼티가 없습니다.
이번에 제가 짠 코드는 userInfo 값을 입력 받기만 하면되기 때문에 이전 값을 저장할 필요가 없다고 판단하여 PublishRelay를 사용했습니다.

2022-11-01 02:30 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/LoginManagerProtocol.swift
> +    var loginstatus: PublishRelay<Loginstatus> { get }
https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/28#discussion_r1010018105 
참고 부탁드립니다 !

2022-11-01 02:32 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewController.swift
> +                        self.testView.userImageView.isHidden = true
저는 self 붙이는 게 명시적이라 거의 다 붙였었는데, 에코가 말씀하신대로 일관성이 없었다고 생각이 드네요
###  상속받은 속성의 경우는 self를 붙여주고 직접 구현한 속성은 self를 붙이지 않습니다.
말씀해주신 대로 self 주의해서 붙이도록 하겠습니다 감사합니다 :)

2022-11-01 02:44 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginManager.swift
> +    func unlink() {
카카오에서 unlink 함수를 사용해서 통용적으로 탈퇴를 unlink라고 쓰는 줄 알았습니다..!
파파고형님한테 물어봤더니 withDrawal 라고 하네요, (레몬도 withDrawal라고 사용했습니다)
unlink -> withDrawal로 변경하겠습니다 !

2022-11-01 02:51 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginManager.swift
> +            .subscribe(onSuccess: { user in
struct 이라서 강한순환참조가 안 일어난다고 생각했습니다 ..! 혹시 강한순환참조를 해야 하는 이유를 말씀해주실 수 있을까요 ?

2022-11-01 02:53 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginManager.swift
> +                self.userInfo.accept(UserInfo(id: UUID().uuidString, name: "로그아웃 성공", imageURL: nil))
저 코드 유저 데이터 띄우는 게 아니라 지금 임시로 "로그아웃 성공, 회원 탈퇴 성공"을 화면에 띄울려고 만들어 둔거라서 MockData까지는 필요 없을 것 같습니다..!

<img width="199" alt="스크린샷 2022-11-01 오전 11 52 32" src="https://user-images.githubusercontent.com/82457928/199148378-2f4bce1b-3692-420f-9f34-cb92802cf930.png">

2022-11-01 06:28 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewController.swift
> +                .disposed(by: self.disposeBag)
수정했습니다 !

2022-11-01 06:29 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewController.swift
> +                    print("토큰 유효성 체크 성공(필요 시 토큰 갱신됨)")
issue로 빼두고 후에 pr 작업해서 올리겠습니다 !

2022-11-01 06:54 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewController.swift
> +                .disposed(by: self.disposeBag)
수정했습니다 !

2022-11-01 06:55 UTC, rriver2 commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginViewController.swift
> +                    print("토큰 유효성 체크 성공(필요 시 토큰 갱신됨)")
issue를 남기고 다른 pr로 해당 내용 구현하겠습니다 ! 감사합니다 :)

2022-11-01 07:35 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginManager.swift
> +            .subscribe(onSuccess: { user in
> struct 이라서 강한순환참조가 안 일어난다고 생각했습니다 ..! 혹시 강한순환참조를 해야 하는 이유를 말씀해주실 수 있을까요 ?

제가 잘못보았네요. 죄송욧

2022-11-01 07:37 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/kakaoLoginTest/KakaoLoginManager.swift
> +    let userInfo: PublishRelay<UserInfo> = .init()
근거로는 이게 되겠네요!
https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/28#issuecomment-1296168023

2022-11-01 08:22 UTC, merged