Feat/#14 apple login
DeveloperAcademy-POSTECH/MacC_Team_Beartear pull request #31
Opened 2022-10-27 06:54 UTC by SH0123

## Close Issues
- Pull Request와 관련된 Issue가 있다면 나열합니다.
🔒 Close #14

## 작업 내용 (Content)
- [x] 프로젝트 signing 추가
- [x] certificates에 id 등록, apple developer에서 firebase 도메인 입력
- [x] apple 로그인 담당 객체 생성하여 로직 구성
- [x] 테스트 UI (로그인 버튼, 로그아웃 버튼, 탈퇴 버튼, 로그인 이후 계정 정보 표시 UI)
- [x] 팀 provisioning profile 

## Review points
- addSubview, layout등의 작업을 하는 함수명이 제각각 달라서 통일하면 좋을 것 같습니다
- apple login 모달 때문에 apple login manager에 viewController를 주입해줬습니다. 이 과정에서 순환 참조 발생이 우려되어 vc를 약한 참조하였습니다.
- ASAuthorizationControllerPresentationContextProviding은 apple login 모달을 어느 window에서 띄울지 결정하는 곳입니다.
아래와 같이 force unwrapping을 하였는데 공식문서에서도 이렇게 진행했고 제 판단에도 viewController가 존재하지 않을 수는 없다고 생각하여 force하게 하였습니다. 혹시나 우려되는 사항이 있거나 다른 방안이 있으면 조언 부탁드립니다
```swift
return viewController!.view.window!
```

## 기타 사항 (Etc)
- Rx로 구현은 조금 더 공부한 뒤에 구현하도록 하겠습니다
- 현재는 로그인, 로그아웃, 탈퇴 기능만 구현하였고 자동 로그인 관련 기능은 추후 구현하겠습니다. 이와 관련하여 고민한 내용은 discussion에 올리겠습니다
- issue #30에서 추후 구현할 사항들을 정리했습니다

## 관련 사진 gif 및 (Optional)

## References (Optional)
- [provisioning profile](https://rriver2.tistory.com/entry/협업할-때-Certificate-Provisioning-Profiles-개념-실습)
- [apple login 브랜디](https://labs.brandi.co.kr/2021/04/09/chosh.html)
- [apple login 공식 문서](https://developer.apple.com/documentation/authenticationservices/implementing_user_authentication_with_sign_in_with_apple)
- [apple login과 firebase](https://firebase.google.com/docs/auth/ios/apple)

2022-10-28 11:10 UTC, HoJongE approved these changes
잘되면 머지하세요~~

2022-10-28 11:16 UTC, SH0123 commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestViewController.swift
> +        appleTestView.appleWithdrawalButton.addTarget(self, action: #selector(tapAppleWithdrawalButton), for: .touchUpInside)
네 해당 rx 부분 참고하고 공부해서 반영해보겠습니다 ~

2022-10-28 11:16 UTC, SH0123 commented on Gom4ziz/Gom4ziz/Domain/Model/AppleLoginManager.swift
> +    weak var delegate: AppleLoginManagerDelegate?
오 감사합니다 ~

2022-10-30 07:24 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestViewController.swift
> +    }
나중에 리버와 리팩토링할 때, ViewModel 의 함수를 호출하는 형식으로 바꾸면 될 것 같습니다~~

2022-10-30 07:26 UTC, HoJongE approved these changes
수정 필수 고치고 머지하시면 될 것 같아요~~

2022-10-30 07:26 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestView.swift
> +import UIKit
[수정필수]
이 부분 import 규칙 신경써주세요~~

2022-10-30 08:08 UTC, imparang requested changes
수고하셨습니다.
코드의 일관성을 위해 이야기를 나눠봐야겠군요!

2022-10-30 08:08 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestViewController.swift
> +import Foundation
[수정필수]
UIKit 안에 Foundation이 있어요!
Foundation은 지워주세요.

Foundation은 UI를 제외한 앱의 중심 기능(자료형, 네트워킹, 타이머 등)을 가지고 있는 프레임워크고
UIKit은 UI(화면)과 관련된 기능(Window, View 등)과 Foundation을 가지고 있는 프레임워크 입니다.

2022-10-30 08:08 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestViewController.swift
> +    private lazy var appleLoginManager: AppleLoginManager = {
[질문]
lazy var로 manager를 선언해주신 이유가 무엇일까요?

2022-10-30 08:08 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestViewController.swift
> +        appleLoginManager.delegate = self
[수정고려]
viewDidLoad에서는 메서드만 호출하는 형태로 정리하면 어떨까 싶습니다.
`appleLoginManager.delegate = self`는 setAppleLoginManager 라던지 어떠한 메서드 내부에서 구현해서 말이죠.

2022-10-30 08:08 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestView.swift
> +        backgroundColor = .systemBackground
[수정고려]
아래 self.addSubView에서는 self를 쓰셨는데, 여기도 써주세욘

2022-10-30 08:08 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestView.swift
> +
얘기를 나눠봐야할 부분이긴 한디 누구는 configure, 누구는 set으로 사용하고 있어서 이야기 해봐야겠네요.
@HoJongE @rriver2

2022-10-30 08:08 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestViewController.swift
> +        appleTestView.appleWithdrawalButton.addTarget(self, action: #selector(tapAppleWithdrawalButton), for: .touchUpInside)
rx.tap으로 처리하면 좋을 것 같습니다.

2022-10-30 14:22 UTC, SH0123 commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestView.swift
> +import UIKit
AuthenticationService 애플 기본 모듈인데 import 규칙 혹시 어떻게 되나용

2022-10-30 14:23 UTC, SH0123 commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestViewController.swift
> +    private lazy var appleLoginManager: AppleLoginManager = {
AppleTestViewController인 self를 applelLoginManager 생성시에 주입해줘야해서 lazy로 선언했습니다

2022-10-30 14:24 UTC, SH0123 commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestViewController.swift
> +        appleLoginManager.delegate = self
좋습니다 !! 테스트용 UI여서 간략하게 나타낸것이니 후에 제대로된 UI 코드를 작성하게 된다면 그렇게 하는게 저도 좋다고 생각합니당

2022-10-30 14:25 UTC, SH0123 commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestView.swift
> +        backgroundColor = .systemBackground
에코 나름의 self를 쓰는 규칙, 기준이 있던데 저도 이야기 듣고 그렇게 해보고싶네요 ~ 나중에 대면으로 알려주시면 감사하겠습니당

2022-10-30 14:45 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestView.swift
> +        backgroundColor = .systemBackground
> 에코 나름의 self를 쓰는 규칙, 기준이 있던데 저도 이야기 듣고 그렇게 해보고싶네요 ~ 나중에 대면으로 알려주시면 감사하겠습니당

저는 이런식으로 합니당
https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/28#discussion_r1008807211

2022-10-30 14:53 UTC, imparang commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestView.swift
> +import UIKit
퍼스트 파티면 그대로 해도 되겠네요..! 

참고해주세요.
https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/pull/20#discussion_r1003888228

2022-10-30 15:10 UTC, SH0123 commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestViewController.swift
> +        appleTestView.appleWithdrawalButton.addTarget(self, action: #selector(tapAppleWithdrawalButton), for: .touchUpInside)
rx extension을 사용하는것이 addTarget보다 좋은점, 사용하는 이유가 뭐가 있을지 설명해주실 수 있을까요?

2022-10-31 01:36 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestView.swift
> +import UIKit
그럼 오키

2022-10-31 01:37 UTC, SH0123 commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestViewController.swift
> +        appleLoginManager.delegate = self
좋습니다 !! 테스트용 UI여서 간략하게 나타낸것이니 후에 제대로된 UI 코드를 작성하게 된다면 그렇게 하는게 저도 좋다고 생각합니다

2022-10-31 01:38 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestView.swift
> +
이건 제가 Base UIView 를 구현해서 그것만 공유하면 될 것 같아요!

2022-10-31 01:40 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestViewController.swift
> +        appleTestView.appleWithdrawalButton.addTarget(self, action: #selector(tapAppleWithdrawalButton), for: .touchUpInside)
addTarget 은 objc 코드를 넣어야 되잖아요. 또한 이벤트도 추가해줘야 하잖아요. swift 스럽지 않습니다. 또한 rx.tap 은 연산자를 추가해서 계속해서 따른 작업으로 손쉽게 연결할 수 있으므로, 가독성도 좋다고 생각해요.

2022-10-31 06:56 UTC, SH0123 commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestViewController.swift
> +        appleTestView.appleWithdrawalButton.addTarget(self, action: #selector(tapAppleWithdrawalButton), for: .touchUpInside)
rx로 전반적인 교체 과정을 차근차근 진행하고 새로운 pr로 날리도록 할 계획이었으니 추후 작업에서 진행하겠습니다 ~

2022-10-31 07:00 UTC, SH0123 commented on Gom4ziz/Gom4ziz/Domain/Model/AppleLoginManager.swift
> +    init(vc: UIViewController) {
440a067ec66c60eef64005ce93d8ff3947310b04 반영 완료하였습니다

2022-10-31 07:00 UTC, SH0123 commented on Gom4ziz/Gom4ziz/Presenter/AppleLoginTest/AppleTestViewController.swift
> +import Foundation
440a067ec66c60eef64005ce93d8ff3947310b04 반영 완료하였습니다

2022-11-01 07:28 UTC, imparang approved these changes
LGTM

2022-11-01 07:38 UTC, merged