Feat: Add Utility code to share
DeveloperAcademy-POSTECH/MacC_Team_Beartear pull request #32
Opened 2022-10-30 08:49 UTC by HoJongE

## 작업 내용 (Content)

- **BaseRxViewController** 추가 -> ViewModel 혹은 다른 Observable 의 구독을 설정하는 setUpObserver 함수 추가 및 자동으로 호출하게 해놓음 (프로토콜이라 구현만 하면 됨)
- **BaseAutoLayoutUIView** 추가  -> 자식 뷰들을 추가하고, 제약조건을 거는 함수들을 추가. 그리고 해당 함수들을 자동으로 호출한다. 마찬가지로 protocol 이라서 구현만 하면 됨
- 비동기적으로 가져오는 타입의 데이터와 상태를 한 번에 나타낼 수 있는 **Loadable enumeration** 추가

## Review points
- [BaseAutoLayoutUIView 를 사용하는 방법](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/compare/develop...DeveloperAcademy-POSTECH:Feat%2F_add_utility_codes?expand=1&title=Feat%3A%20Add%20Utility%20code%20to%20share%20&body=%23%23%20Close%20Issues%0A-%20Pull%20Request와%20관련된%20Issue가%20있다면%20나열합니다.%0A%F0%9F%94%92%20Close%20%23number%0A%0A%23%23%20작업%20내용%20(Content)%0A-%20작업한%20내용을%20나열%20후%20설명%0A%0A%23%23%20Review%20points%0A-%20리뷰어가%20중점적으로%20리뷰해줬으면%20하는%20포인트%0A%0A%23%23%20기타%20사항%20(Etc)%0A-%20작업하면서%20고민이%20되었던%20부분이나%20질문%20사항%20등%0A%0A%23%23%20관련%20사진%20gif%20및%20(Optional)%0A%0A%23%23%20References%20(Optional)%0A-%20참고한%20사이트나%20정리한%20wiki%20링크를%20넣어주세요%0A-%20%5B링크이름%5D(링크)%0A#diff-2bd98a333d06ba47f3f1f3a1506fa2321a84d8927f466f7d861346ef98113e11R10-R42)

자식뷰를 추가하고, 오토레이아웃 제약조건을 거는 함수를 가지고 있는 protocol 을 구현하고, 만약 자기가 해당 프로토콜 타입이면 자동으로 해당 함수를 init 단계에서 호출하는 UIView 를 혼합한 type 입니다. 따라서 만약 BaseAutoLayoutUIView 를 상속하게 되면, 프로토콜과 AutoLayoutUIView를 자동으로 상속하게 되며, 자동으로 자식뷰 추가와 제약조건 함수를 호출하게 됩니다. 따라서 모두의 스타일을 통일할 수 있고, 굳이 함수 호출 코드를 작성하지 않아도 됩니다.
- [BaseRxViewController 를 사용하는 방법](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/compare/develop...DeveloperAcademy-POSTECH:Feat%2F_add_utility_codes?expand=1&title=Feat%3A%20Add%20Utility%20code%20to%20share%20&body=%23%23%20Close%20Issues%0A-%20Pull%20Request와%20관련된%20Issue가%20있다면%20나열합니다.%0A%F0%9F%94%92%20Close%20%23number%0A%0A%23%23%20작업%20내용%20(Content)%0A-%20작업한%20내용을%20나열%20후%20설명%0A%0A%23%23%20Review%20points%0A-%20리뷰어가%20중점적으로%20리뷰해줬으면%20하는%20포인트%0A%0A%23%23%20기타%20사항%20(Etc)%0A-%20작업하면서%20고민이%20되었던%20부분이나%20질문%20사항%20등%0A%0A%23%23%20관련%20사진%20gif%20및%20(Optional)%0A%0A%23%23%20References%20(Optional)%0A-%20참고한%20사이트나%20정리한%20wiki%20링크를%20넣어주세요%0A-%20%5B링크이름%5D(링크)%0A#diff-d4123077fe61d07f9ef991c96366f5516d40a775cb3ca3a80a655616af81bb4bR10-R25)

ViewModel 혹은 다른 Observable에게 옵저버를 추가하는 함수를 가지고 있는 protocol 을 구현하고, 만약 자기가 해당 프로토콜 타입이면 자동으로 해당 함수를 viewDidLoad 단계에서 호출하는 뷰컨을 혼합한 type 입니다. 따라서 만약 BaseRxViewController 를 상속하게 되면, 프로토콜과 RxViewController 를 자동으로 상속하게 되며, 자동으로 옵저버를 추가하는 함수를 호출하게 됩니다. 따라서 모두의 스타일을 통일할 수 있고, 굳이 함수 호출 코드를 작성하지 않아도 됩니다.

- [Loadable enumeration](https://github.com/DeveloperAcademy-POSTECH/MacC_Team_Beartear/compare/develop...DeveloperAcademy-POSTECH:Feat%2F_add_utility_codes?expand=1&title=Feat%3A%20Add%20Utility%20code%20to%20share%20&body=%23%23%20Close%20Issues%0A-%20Pull%20Request와%20관련된%20Issue가%20있다면%20나열합니다.%0A%F0%9F%94%92%20Close%20%23number%0A%0A%23%23%20작업%20내용%20(Content)%0A-%20작업한%20내용을%20나열%20후%20설명%0A%0A%23%23%20Review%20points%0A-%20리뷰어가%20중점적으로%20리뷰해줬으면%20하는%20포인트%0A%0A%23%23%20기타%20사항%20(Etc)%0A-%20작업하면서%20고민이%20되었던%20부분이나%20질문%20사항%20등%0A%0A%23%23%20관련%20사진%20gif%20및%20(Optional)%0A%0A%23%23%20References%20(Optional)%0A-%20참고한%20사이트나%20정리한%20wiki%20링크를%20넣어주세요%0A-%20%5B링크이름%5D(링크)%0A#diff-f99d753f93468c0f9dd48634bbabd5f2c01fe5676536319539dbb74bb52a34f5R8-R105)

기존에 우리는 비동기적으로 받아오는 데이터들이 있으면, 해당 데이터를 받아오는 상태를 표시하기 위해 추가적인 프로퍼티들을 선언했었습니다.

```swift
@Published private (set) var isLoading: Bool
@Published private (set) var isError: Error?
```

그러나 위와 같이 이벤트의 상태를 나타내는 것의 단점은, 데이터의 상태와 이벤트의 상태가 일치하지 않을 수 있다는 점입니다. 
예를 들어, 데이터를 불러오기 위해 isLoading 을 true 로 바꿨는데, 나중에 데이터를 성공적으로 받았음에도 프로그래머가 isLoading 을 다시 false 로 변경하지 않으면, 데이터는 로딩되있지만 프로그레스바가 계속해서 돌아가는 현상이 발생합니다. 

그러나 데이터의 이벤트의 상태를 동시에 묶으면 (Loadable), 이 두 가지 상태가 일치하지 않을 가능성이 없어집니다. 가독성도 좋아지며, 많은 Boiler plate 코드를 제거할 수 있습니다.

## 기타 사항 (Etc)

## 관련 사진 gif 및 (Optional)

## References (Optional)

2022-10-30 11:38 UTC, imparang requested changes
고생하셨습니다.
Base를 만들어서 사용하는거 좋습니당

2022-10-30 11:38 UTC, imparang commented on Gom4ziz/Gom4ziz/Utility/AutoLayoutUIView.swift
> +class AutoLayoutUIView: UIView {
[고려]
기왕 BaseView 만드는 거 view layout 관련 말고 view configuration 관련된 메소드고 구현해두면 좋지 않을까요?
예를들면 navigation을 사용하게 되면 작성해줘야 하는 내용들이 있으니까요

2022-10-30 11:38 UTC, imparang commented on Gom4ziz/Gom4ziz/Utility/Loadable.swift
> +        case .loaded(let t):
[수정필수]
단순히 연관값을 t로 하면 이해하기 힘들 것 같습니다.
좀 더 구체적으로 변경 부탁드려요!

2022-10-31 01:27 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Utility/AutoLayoutUIView.swift
> +class AutoLayoutUIView: UIView {
그게뭐죠

2022-10-31 02:34 UTC, SH0123 approved these changes

2022-10-31 02:34 UTC, SH0123 commented on Gom4ziz/Gom4ziz/Utility/Loadable.swift
> +    static func == (lhs: Loadable<T>, rhs: Loadable<T>) -> Bool {
[질문]
loadable, loading 관련 상태를 다뤄본 적이 없어서 질문 드립니다.
loadable enum을 == 연산자 비교를 해야하는 경우 예시 들어주세요

2022-10-31 02:34 UTC, SH0123 commented on Gom4ziz/Gom4ziz/Utility/Loadable.swift
> +                    return .isLoading(last: try value.map { try transform($0) })
[질문]
value가 배열이 아닌데 value.map을 어떻게 사용한건지 궁금합니다!!
코드상 문제가 없는 것으로 보면 제가 놓치고있는 부분이 있는 것 같은데 알려주세요!

2022-10-31 08:00 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Utility/Loadable.swift
> +    static func == (lhs: Loadable<T>, rhs: Loadable<T>) -> Bool {
SwiftUI의 onChange의 경우 Equatable 을 채택한 타입만 변경을 감지할 수 있습니다.
또한 기타 많은 다른 함수들도 Equatable 을 채택한 타입을 요구하는 경우가 많습니다.

2022-10-31 08:03 UTC, HoJongE commented on Gom4ziz/Gom4ziz/Utility/Loadable.swift
> +                    return .isLoading(last: try value.map { try transform($0) })
value 는 T? 타입으로 Optional엔 값을 unwrapping 하는 map 함수가 존재합니다. Collection 에 있는 map 함수랑 달라요.

2022-10-31 14:27 UTC, yungahui commented
정말 멋지군요 여러분

2022-11-01 07:31 UTC, imparang approved these changes
수고하셨습니다.

2022-11-01 08:35 UTC, merged