feat: #80 FetchReviewedArtworkUsecase와 requestReviewedArtworkList 구현
DeveloperAcademy-POSTECH/MacC_Team_Beartear pull request #87
Opened 2022-11-22 07:57 UTC by rriver2

## Close Issues
- Pull Request와 관련된 Issue가 있다면 나열합니다.
🔒 Close #80 

## 작업 내용 (Content)
- 작업한 내용을 나열 후 설명
이번 PR에서는 하단의 이미지에 있는 FetchReviewedArtworkUsecase와 ArtworkRepository를 구현했습니다.
DB에서 Review된 Artwork들을 불러오기 위해서 FetchReviewedArtworkUsecase에서 ArtworkRepository의 fetchReviewedArtworkList(lastArtworkId)을 호출하여, ReviewedArtworkList를 반환 받는 코드를 작성했습니다.
<img width="819" alt="스크린샷 2022-11-22 오후 4 38 12" src="https://user-images.githubusercontent.com/82457928/203256679-b1187eb9-db78-4d7d-9fb9-2bba648a6bcf.png">

**[고민사항]**
<img width="100" alt="스크린샷 2022-11-22 오후 4 55 45" src="https://user-images.githubusercontent.com/82457928/203257062-529268dd-3f3d-4fa2-8d73-22090f8de56e.png">
lastArtworkId 값을 넣는 부분은 후에 레이몬드와 좀 더 상의를 해봐야할 것 같습니다.
위 View에서 질문 나오는 컴포넌트와 리뷰한 작품들을 보여주는 컴포넌트를 같은 Viewmodel을 쓰고 그 Viewmodel 안에 lastArtworkId을 저장해두고 공유해서 사용할지, 
아니면 두 컴포넌트의  Viewmodel을 분리할지 고민 중에 있습니다. 후자의 경우에는 어떻게 데이터를 가져와야 하는지 머릿속에 그려지지가 않습니다.. 저와 토론해주실 @SH0123 구합니다. 

## Review points
- 리뷰어가 중점적으로 리뷰해줬으면 하는 포인트
- 데이터 구조, naming 중심으로 봐주세요..!

## 기타 사항 (Etc)
- 작업하면서 고민이 되었던 부분이나 질문 사항 등
**[질문]**
작동하는지 테스트 한다고 firebase에 값 넣어놨는데 삭제해야 하나요 ?
<img width="1140" alt="스크린샷 2022-11-22 오후 4 54 03" src="https://user-images.githubusercontent.com/82457928/203256734-0bcf49aa-f3e8-4033-97ee-30ea46d05e31.png">

## 관련 사진 gif 및 (Optional)

## References (Optional)
- 참고한 사이트나 정리한 wiki 링크를 넣어주세요
[Firebase collection 에서 필요한 document만 filtering 하기 위해서 찾아봤던 문서](https://cloud.google.com/firestore/docs/query-data/queries#swift)입니다.
-> 이번 pr에서는 리뷰된 Artwork만 filtering 해오기 위해 lastArtworkId보다 작은 Artwork만 가져오도록 사용했습니다.

2022-11-22 08:07 UTC, imparang requested changes
수고하셨습니다.
몇가지 고려해보시고 수정해주세용.
그리고 제목!!!! 신경써주세용

2022-11-22 08:07 UTC, imparang commented on Gom4ziz/Source/Data/Repository/FirebaseArtworkRepository.swift
> +        Observable<[Artwork]>.create { [self] observer in
[수정 필수]
RxSwift+Firebase Extension에서 따로 관리해주면 좋을 것 같아요.
필요한 부분이 있다면 그쪽에서 추가해서 사용하면 관리하기 편할 것 같습니다.

2022-11-22 08:07 UTC, imparang commented on Gom4ziz/Source/Data/Repository/FirebaseArtworkRepository.swift
> +    private let collectionName: String = CollectionName.artwork
[수정 고려]
CollectionName.artwork가 따로 있는데 굳이 collectionName을 만들어야 할까요?

2022-11-22 08:12 UTC, rriver2 commented on Gom4ziz/Source/Data/Repository/FirebaseArtworkRepository.swift
> +    private let collectionName: String = CollectionName.artwork
상효보이 코드에서 이렇게 구현되어 있는데 FirebaseArtworkRepository에서는 collectionName이 하나만 사용되기 때문에 괜찮은 거 같아 가져왔습니다.

2022-11-22 14:49 UTC, HoJongE approved these changes
고생하셨습니다~~~

의혹이 가는 부분 빼고는 전체적으로 양호하군요

2022-11-23 00:22 UTC, imparang approved these changes
수고하셨습니다.
반영하신 부분 답글로 커밋번호도 남겨주세요..!

2022-11-23 00:49 UTC, HoJongE commented
DB에 등록한 작품은 삭제할 필요가 없어보여요!

2022-11-23 01:08 UTC, merged